/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vlcproxy;

import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aluno
 */
public class MainWindow extends javax.swing.JDialog {

    /**
     * Creates new form MainWindow
     */
    public MainWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipServidor = new javax.swing.JTextField();
        priori1 = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        portaServidor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ipCliente1 = new javax.swing.JTextField();
        portaCliente1 = new javax.swing.JTextField();
        iniciar1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ipCliente2 = new javax.swing.JTextField();
        portaCliente2 = new javax.swing.JTextField();
        iniciar2 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        priori2 = new javax.swing.JCheckBox();
        ipCliente3 = new javax.swing.JTextField();
        portaCliente3 = new javax.swing.JTextField();
        iniciar3 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        priori3 = new javax.swing.JCheckBox();
        ipCliente5 = new javax.swing.JTextField();
        portaCliente5 = new javax.swing.JTextField();
        iniciar5 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        priori5 = new javax.swing.JCheckBox();
        ipCliente6 = new javax.swing.JTextField();
        portaCliente6 = new javax.swing.JTextField();
        iniciar6 = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        priori6 = new javax.swing.JCheckBox();
        ipCliente4 = new javax.swing.JTextField();
        portaCliente4 = new javax.swing.JTextField();
        iniciar4 = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        priori4 = new javax.swing.JCheckBox();
        ipCliente8 = new javax.swing.JTextField();
        portaCliente8 = new javax.swing.JTextField();
        iniciar8 = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        priori8 = new javax.swing.JCheckBox();
        ipCliente7 = new javax.swing.JTextField();
        portaCliente7 = new javax.swing.JTextField();
        iniciar7 = new javax.swing.JToggleButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        priori7 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ipServidor.setText("127.0.0.1");
        ipServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipServidorActionPerformed(evt);
            }
        });

        priori1.setText("Prioridade");
        priori1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Iniciar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Servidor");

        jLabel2.setText("IP");

        jLabel3.setText("Porta");

        portaServidor.setText("5000");

        jLabel4.setText("Clientes");

        ipCliente1.setText("127.0.0.1");
        ipCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente1ActionPerformed(evt);
            }
        });

        portaCliente1.setText("6000");
        portaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente1ActionPerformed(evt);
            }
        });

        iniciar1.setText("Iniciar");
        iniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar1ActionPerformed(evt);
            }
        });

        jLabel5.setText("IP");

        jLabel6.setText("Porta");

        ipCliente2.setText("127.0.0.1");
        ipCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente2ActionPerformed(evt);
            }
        });

        portaCliente2.setText("6000");
        portaCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente2ActionPerformed(evt);
            }
        });

        iniciar2.setText("Iniciar");
        iniciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar2ActionPerformed(evt);
            }
        });

        jLabel8.setText("IP");

        jLabel9.setText("Porta");

        priori2.setText("Prioridade");
        priori2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori2ActionPerformed(evt);
            }
        });

        ipCliente3.setText("127.0.0.1");
        ipCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente3ActionPerformed(evt);
            }
        });

        portaCliente3.setText("6000");
        portaCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente3ActionPerformed(evt);
            }
        });

        iniciar3.setText("Iniciar");
        iniciar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar3ActionPerformed(evt);
            }
        });

        jLabel11.setText("IP");

        jLabel12.setText("Porta");

        priori3.setText("Prioridade");
        priori3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori3ActionPerformed(evt);
            }
        });

        ipCliente5.setText("127.0.0.1");
        ipCliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente5ActionPerformed(evt);
            }
        });

        portaCliente5.setText("6000");
        portaCliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente5ActionPerformed(evt);
            }
        });

        iniciar5.setText("Iniciar");
        iniciar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar5ActionPerformed(evt);
            }
        });

        jLabel14.setText("IP");

        jLabel15.setText("Porta");

        priori5.setText("Prioridade");
        priori5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori5ActionPerformed(evt);
            }
        });

        ipCliente6.setText("127.0.0.1");
        ipCliente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente6ActionPerformed(evt);
            }
        });

        portaCliente6.setText("6000");
        portaCliente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente6ActionPerformed(evt);
            }
        });

        iniciar6.setText("Iniciar");
        iniciar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar6ActionPerformed(evt);
            }
        });

        jLabel17.setText("IP");

        jLabel18.setText("Porta");

        priori6.setText("Prioridade");
        priori6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori6ActionPerformed(evt);
            }
        });

        ipCliente4.setText("127.0.0.1");
        ipCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente4ActionPerformed(evt);
            }
        });

        portaCliente4.setText("6000");
        portaCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente4ActionPerformed(evt);
            }
        });

        iniciar4.setText("Iniciar");
        iniciar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar4ActionPerformed(evt);
            }
        });

        jLabel20.setText("IP");

        jLabel21.setText("Porta");

        priori4.setText("Prioridade");
        priori4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori4ActionPerformed(evt);
            }
        });

        ipCliente8.setText("127.0.0.1");
        ipCliente8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente8ActionPerformed(evt);
            }
        });

        portaCliente8.setText("6000");
        portaCliente8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente8ActionPerformed(evt);
            }
        });

        iniciar8.setText("Iniciar");
        iniciar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar8ActionPerformed(evt);
            }
        });

        jLabel23.setText("IP");

        jLabel24.setText("Porta");

        priori8.setText("Prioridade");
        priori8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori8ActionPerformed(evt);
            }
        });

        ipCliente7.setText("127.0.0.1");
        ipCliente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipCliente7ActionPerformed(evt);
            }
        });

        portaCliente7.setText("6000");
        portaCliente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaCliente7ActionPerformed(evt);
            }
        });

        iniciar7.setText("Iniciar");
        iniciar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar7ActionPerformed(evt);
            }
        });

        jLabel29.setText("IP");

        jLabel30.setText("Porta");

        priori7.setText("Prioridade");
        priori7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priori7ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ipServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(portaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ipCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(portaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(109, 109, 109)
                                    .addComponent(priori1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iniciar1))
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portaCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(priori6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciar6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portaCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(priori5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciar5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portaCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(priori4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciar4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portaCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(priori3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciar3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(priori2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciar2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portaCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(priori7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciar7)))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portaCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(priori8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iniciar8)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(portaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(portaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar1)
                    .addComponent(priori1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(portaCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar2)
                    .addComponent(priori2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(portaCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar3)
                    .addComponent(priori3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(portaCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar4)
                    .addComponent(priori4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(portaCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar5)
                    .addComponent(priori5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(portaCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar6)
                    .addComponent(priori6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(portaCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar7)
                    .addComponent(priori7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(portaCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciar8)
                    .addComponent(priori8))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priori1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {
            // TODO add your handling code here:
            sinc.AddProdutor(Integer.parseInt(portaServidor.getText()), buffer);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ipServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipServidorActionPerformed

    private void ipCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente1ActionPerformed

    private void iniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar1ActionPerformed
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente1.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente1.getText()), addr, buffer, priori1.isSelected(), 0);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar1ActionPerformed

    private void portaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente1ActionPerformed

    private void ipCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente2ActionPerformed

    private void portaCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente2ActionPerformed

    private void iniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente2.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente2.getText()), addr, buffer, priori2.isSelected(), 1);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar2ActionPerformed

    private void priori2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori2ActionPerformed

    private void ipCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente3ActionPerformed

    private void portaCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente3ActionPerformed

    private void iniciar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente3.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente3.getText()), addr, buffer, priori3.isSelected(), 2);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar3ActionPerformed

    private void priori3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori3ActionPerformed

    private void ipCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente5ActionPerformed

    private void portaCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente5ActionPerformed

    private void iniciar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente5.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente5.getText()), addr, buffer, priori5.isSelected(), 4);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar5ActionPerformed

    private void priori5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori5ActionPerformed

    private void ipCliente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente6ActionPerformed

    private void portaCliente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente6ActionPerformed

    private void iniciar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar6ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente6.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente6.getText()), addr, buffer, priori6.isSelected(), 5);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar6ActionPerformed

    private void priori6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori6ActionPerformed

    private void ipCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente4ActionPerformed

    private void portaCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente4ActionPerformed

    private void iniciar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente4.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente4.getText()), addr, buffer, priori4.isSelected(), 3);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar4ActionPerformed

    private void priori4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori4ActionPerformed

    private void ipCliente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente8ActionPerformed

    private void portaCliente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente8ActionPerformed

    private void iniciar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar8ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente8.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente8.getText()), addr, buffer, priori8.isSelected(), 7);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar8ActionPerformed

    private void priori8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori8ActionPerformed

    private void ipCliente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipCliente7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipCliente7ActionPerformed

    private void portaCliente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaCliente7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portaCliente7ActionPerformed

    private void iniciar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar7ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            addr = InetAddress.getByName(ipCliente7.getText());
            sinc.AddConsumidor(Integer.parseInt(portaCliente7.getText()), addr, buffer, priori7.isSelected(), 6);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciar7ActionPerformed

    private void priori7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priori7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priori7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            sinc.AddProdutor(Integer.parseInt(portaServidor.getText()), buffer);
        } catch (SocketException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow dialog = new MainWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    Sincronizador sinc;
    static Buffer buffer;
    static Semaphore sem;
    InetAddress addr;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton iniciar1;
    private javax.swing.JToggleButton iniciar2;
    private javax.swing.JToggleButton iniciar3;
    private javax.swing.JToggleButton iniciar4;
    private javax.swing.JToggleButton iniciar5;
    private javax.swing.JToggleButton iniciar6;
    private javax.swing.JToggleButton iniciar7;
    private javax.swing.JToggleButton iniciar8;
    private javax.swing.JTextField ipCliente1;
    private javax.swing.JTextField ipCliente2;
    private javax.swing.JTextField ipCliente3;
    private javax.swing.JTextField ipCliente4;
    private javax.swing.JTextField ipCliente5;
    private javax.swing.JTextField ipCliente6;
    private javax.swing.JTextField ipCliente7;
    private javax.swing.JTextField ipCliente8;
    private javax.swing.JTextField ipServidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField portaCliente1;
    private javax.swing.JTextField portaCliente2;
    private javax.swing.JTextField portaCliente3;
    private javax.swing.JTextField portaCliente4;
    private javax.swing.JTextField portaCliente5;
    private javax.swing.JTextField portaCliente6;
    private javax.swing.JTextField portaCliente7;
    private javax.swing.JTextField portaCliente8;
    private javax.swing.JTextField portaServidor;
    private javax.swing.JCheckBox priori1;
    private javax.swing.JCheckBox priori2;
    private javax.swing.JCheckBox priori3;
    private javax.swing.JCheckBox priori4;
    private javax.swing.JCheckBox priori5;
    private javax.swing.JCheckBox priori6;
    private javax.swing.JCheckBox priori7;
    private javax.swing.JCheckBox priori8;
    // End of variables declaration//GEN-END:variables
}
